# Generated by Django 3.0.1 on 2023-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_auto_20210527_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Monthly bill', 'Monthly bill'), ('Online shopping', 'Online shopping'), ('Electronics', 'Electronics'), ('Groceries', 'Groceries'), ('Taxi fare', 'Taxi fare'), ('Housing', 'Housing'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
    ]
