# Generated by Django 3.0.1 on 2023-08-30 18:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_auto_20230511_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Monthly bill', 'Monthly bill'), ('Online shopping', 'Online shopping'), ('Electronics', 'Electronics'), ('Groceries', 'Groceries'), ('Transport', 'Transport'), ('Housing', 'Housing'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
    ]
